"""
BookingBackendContract — shared behavioral tests every BookingBackend must pass.

Your ReseasyBackend is graded against this same contract that the production
backends pass. Uses the in-memory ResEasy simulator so no live creds are needed.

    pytest tests/test_contract.py -v

>>> DO NOT EDIT THIS FILE. <<<  The grader verifies it is unchanged.
"""

from __future__ import annotations

import time

import pytest

from backends.base import (
    AvailabilityResult,
    BookingBackend,
    render_availability_message,
)


# ---------------------------------------------------------------------------
# Contract mixin — one subclass per backend
# ---------------------------------------------------------------------------


class BookingBackendContract:
    def make_backend(self) -> BookingBackend:
        raise NotImplementedError

    # -- AvailabilityResult structure --

    @pytest.mark.asyncio
    async def test_get_availability_returns_correct_type(self):
        backend = self.make_backend()
        result = await backend.get_availability("2026-05-01", "19:00", 2)
        assert isinstance(result, AvailabilityResult)
        assert result.date == "2026-05-01"
        assert result.party_size == 2
        assert isinstance(result.alternative_times, list)
        assert isinstance(result.fetched_at_monotonic, float)

    @pytest.mark.asyncio
    async def test_get_availability_exact_available_property(self):
        backend = self.make_backend()
        result = await backend.get_availability("2026-05-01", "19:00", 2)
        assert result.exact_available == (result.exact_match_datetime is not None)

    @pytest.mark.asyncio
    async def test_get_availability_exact_slot_found(self):
        backend = self.make_backend()
        result = await backend.get_availability("2026-05-01", "19:00", 2)
        # 19:00 is seeded as available -> must be an exact match.
        assert result.exact_available
        assert "19:00" in (result.exact_match_datetime or "")

    @pytest.mark.asyncio
    async def test_get_availability_offers_alternatives(self):
        backend = self.make_backend()
        # 18:00 is not seeded; backend should surface other open times.
        result = await backend.get_availability("2026-05-01", "18:00", 2)
        assert not result.exact_available
        assert result.alternative_times  # 19:00 / 19:30 / 20:00

    # -- create_reservation returns (str, str) --

    @pytest.mark.asyncio
    async def test_create_reservation_returns_tuple(self):
        backend = self.make_backend()
        msg, provider_id = await backend.create_reservation(
            "RES-TEST01", "2026-05-01", "19:00", 2, "Ana Silva", "+351912345678"
        )
        assert isinstance(msg, str)
        assert isinstance(provider_id, str)
        assert len(msg) > 0
        assert len(provider_id) > 0

    @pytest.mark.asyncio
    async def test_create_reservation_success_message_contains_confirmed(self):
        backend = self.make_backend()
        msg, _ = await backend.create_reservation(
            "RES-TEST02", "2026-05-01", "19:30", 2, "Ana Silva", "+351912345678"
        )
        # A successful booking must contain "confirmed" so the dispatcher can
        # detect it and fire the post-booking task.
        assert "confirmed" in msg.lower() or "BOOKING_ERROR" in msg

    # -- find_reservation returns str --

    @pytest.mark.asyncio
    async def test_find_reservation_returns_string(self):
        backend = self.make_backend()
        result = await backend.find_reservation("+351900000000")
        assert isinstance(result, str)
        assert len(result) > 0  # even "none found" is a non-empty caller message

    # -- modify_reservation returns str (never raises on bad id) --

    @pytest.mark.asyncio
    async def test_modify_reservation_returns_string(self):
        backend = self.make_backend()
        result = await backend.modify_reservation("FAKE-RES-ID", new_time="20:00")
        assert isinstance(result, str)

    @pytest.mark.asyncio
    async def test_modify_reservation_no_changes(self):
        backend = self.make_backend()
        result = await backend.modify_reservation("FAKE-RES-ID")
        assert "unchanged" in result.lower()

    # -- cancel_reservation returns str (never raises on bad id) --

    @pytest.mark.asyncio
    async def test_cancel_reservation_returns_string(self):
        backend = self.make_backend()
        result = await backend.cancel_reservation("FAKE-RES-ID")
        assert isinstance(result, str)
        assert len(result) > 0

    # -- render helper is consistent (sanity) --

    def test_render_available_slot(self):
        result = AvailabilityResult(
            date="2026-05-01",
            requested_time="19:00",
            requested_hhmm="19:00",
            party_size=2,
            exact_match_datetime="2026-05-01T19:00:00+01:00",
            alternative_times=[],
            fetched_at_monotonic=time.monotonic(),
        )
        msg = render_availability_message(result)
        assert "availability" in msg.lower()


# ---------------------------------------------------------------------------
# ResEasy contract
# ---------------------------------------------------------------------------


class TestReseasyContract(BookingBackendContract):
    def make_backend(self):
        from backends.reseasy import ReseasyBackend
        from backends.reseasy_client import ReseasyClient

        client = ReseasyClient(api_key="test-key")  # default seed = 2026-05-01
        return ReseasyBackend(restaurant_id="r-test", client=client)
