"""
BookingBackend — abstract interface all booking adapters must implement.

All adapters return consistent types so the dispatcher never needs to branch
on backend name to unwrap results.

>>> DO NOT EDIT THIS FILE. <<<
The grader verifies it is unchanged.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass


@dataclass
class AvailabilityResult:
    date: str
    requested_time: str
    requested_hhmm: str
    party_size: int
    exact_match_datetime: str | None
    alternative_times: list[str]
    fetched_at_monotonic: float
    preference: str = "balanced"

    @property
    def exact_available(self) -> bool:
        return self.exact_match_datetime is not None


def render_availability_message(result: AvailabilityResult) -> str:
    """Render an AvailabilityResult as a caller-facing string."""
    if result.exact_available:
        return (
            f"We have availability for {result.party_size} guests on {result.date} at {result.requested_time}. "
            "I can book this now."
        )
    if result.alternative_times:
        alternatives = ", ".join(result.alternative_times)
        return (
            f"Sorry, {result.requested_time} on {result.date} isn't available for {result.party_size} guests. "
            f"Available times: {alternatives}. Would any of those work?"
        )
    return (
        f"Sorry, there are no available tables on {result.date} for {result.party_size} guests. "
        "Would you like to try a different date?"
    )


class BookingBackend(ABC):
    """Abstract booking backend. Each method returns a consistent type."""

    @abstractmethod
    async def get_availability(
        self,
        date: str,
        time_: str,
        party_size: int,
        *,
        preference: str = "balanced",
    ) -> AvailabilityResult: ...

    @abstractmethod
    async def create_reservation(
        self,
        reservation_id: str,
        date: str,
        time_: str,
        party_size: int,
        guest_name: str,
        guest_phone: str,
        guest_email: str = "",
        notes: str = "",
        locale: str = "en_US",
        restaurant_timezone: str = "UTC",
        prefetched_meal_date: str = "",
    ) -> tuple[str, str]: ...  # (caller-facing message, provider_id)

    @abstractmethod
    async def find_reservation(
        self,
        guest_phone: str,
        restaurant_timezone: str = "UTC",
    ) -> str: ...

    @abstractmethod
    async def modify_reservation(
        self,
        reservation_id: str,
        new_date: str = "",
        new_time: str = "",
        new_party_size: int = 0,
        new_notes: str = "",
        restaurant_timezone: str = "UTC",
    ) -> str: ...

    @abstractmethod
    async def cancel_reservation(
        self,
        reservation_id: str,
    ) -> str: ...
