"""
Booking-backend registry.

Each booking provider is a `BookingBackend` subclass that self-registers under
a short name at import time. The dispatcher looks up the backend keyed on
`BookingConfig.backend`, so adding a new provider is a single new file plus a
one-line `register_backend(...)` call. The dispatcher never branches on
provider name.

>>> DO NOT EDIT THIS FILE. <<<
The grader verifies it is unchanged.
"""

from __future__ import annotations

from typing import Callable

from backends.base import BookingBackend

# Factory takes the per-tenant BookingConfig.
BackendFactory = Callable[..., BookingBackend]
# Validator runs at startup against a tenant's BookingConfig and returns None
# when the backend is ready, or a human-readable error otherwise. Validators
# must NOT make network calls — cheap, side-effect-free checks only.
BackendValidator = Callable[..., "str | None"]

_BACKENDS: dict[str, BackendFactory] = {}
_VALIDATORS: dict[str, BackendValidator] = {}


class BookingBackendError(RuntimeError):
    """Raised when a backend cannot be constructed (unknown name, missing creds)."""


def register_backend(
    name: str,
    factory: BackendFactory,
    *,
    validator: BackendValidator | None = None,
) -> None:
    """Register `factory` under `name`. Last registration wins (useful in tests)."""
    _BACKENDS[name] = factory
    if validator is not None:
        _VALIDATORS[name] = validator
    else:
        _VALIDATORS.pop(name, None)


def get_backend(name: str, booking_config) -> BookingBackend:
    """Construct the backend registered under `name`.

    Raises BookingBackendError if `name` is not registered. The factory may
    raise its own BookingBackendError for missing creds.
    """
    factory = _BACKENDS.get(name)
    if factory is None:
        raise BookingBackendError(
            f"BOOKING_ERROR:BACKEND_UNKNOWN - No booking backend registered under "
            f"'{name}'. Registered: {sorted(_BACKENDS) or '[]'}."
        )
    return factory(booking_config)


def validate_backend(name: str, booking_config) -> str | None:
    """Run the backend's startup validator, if any."""
    validator = _VALIDATORS.get(name)
    if validator is None:
        return None
    try:
        return validator(booking_config)
    except Exception as exc:  # validator bugs must never crash startup
        return f"validator for {name!r} raised {type(exc).__name__}: {exc}"


def registered_backends() -> list[str]:
    """Return the sorted list of registered backend names (for diagnostics)."""
    return sorted(_BACKENDS)
